import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { api, login, logout } from './src/api';

const Stack = createNativeStackNavigator();
const Tabs = createBottomTabNavigator();
const green = '#15803d';
const light = '#f0fdf4';

function Header({ title, subtitle }) { return <View style={styles.header}><View><Text style={styles.brand}>AgriNova</Text><Text style={styles.title}>{title}</Text>{subtitle && <Text style={styles.muted}>{subtitle}</Text>}</View><View style={styles.avatar}><Ionicons name="person" size={22} color={green}/></View></View>; }
function Card({ children }) { return <View style={styles.card}>{children}</View>; }
function Action({ icon, title, text, onPress }) { return <Pressable onPress={onPress} style={styles.action}><View style={styles.icon}><Ionicons name={icon} size={24} color={green}/></View><View style={{flex:1}}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.muted}>{text}</Text></View><Ionicons name="chevron-forward" size={20} color="#94a3b8"/></Pressable>; }

function Login({ onDone }) {
 const [identifier,setIdentifier]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async()=>{ if(!identifier||!password)return Alert.alert('Missing details','Enter mobile/email and password.'); setBusy(true); try { await login(identifier,password,'FARMER'); onDone(); } catch(e){Alert.alert('Login failed',e.message);} finally{setBusy(false);} };
 return <View style={styles.login}><Text style={styles.logo}>🌾</Text><Text style={styles.loginTitle}>Welcome to AgriNova</Text><Text style={styles.loginSub}>Your farm-to-city marketplace</Text><TextInput style={styles.input} placeholder="Mobile number or email" value={identifier} onChangeText={setIdentifier} keyboardType="email-address"/><TextInput style={styles.input} placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry/><Pressable style={styles.primary} onPress={submit} disabled={busy}>{busy?<ActivityIndicator color="white"/>:<Text style={styles.primaryText}>Login as Farmer</Text>}</Pressable><Text style={styles.hint}>Your existing AgriNova backend authentication is used.</Text></View>;
}

function Home({ navigation }) { const [prices,setPrices]=useState([]); const [orders,setOrders]=useState([]); useEffect(()=>{(async()=>{try{const p=await api.get('/market-prices');setPrices(p.data||[]);const o=await api.get('/orders');setOrders(o.data||[]);}catch{}})();},[]); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="Farmer Dashboard" subtitle="Sell better. Earn better."/><Card><Text style={styles.section}>Today's market</Text><Text style={styles.big}>{prices[0]?.modal_price ? `₹${prices[0].modal_price}` : 'Live mandi rates'}</Text><Text style={styles.muted}>{prices[0]?.commodity || 'Check current market prices'}</Text><Pressable onPress={()=>navigation.navigate('Market')}><Text style={styles.link}>View market intelligence →</Text></Pressable></Card><Text style={styles.section}>Quick actions</Text><Action icon="add-circle" title="Sell your crop" text="List produce and reach verified buyers" onPress={()=>navigation.navigate('Sell')}/><Action icon="analytics" title="AI market intelligence" text="Compare markets and price trends" onPress={()=>navigation.navigate('Market')}/><Action icon="car" title="Book transportation" text="Arrange farm-to-city delivery" onPress={()=>navigation.navigate('Transport')}/><Action icon="cube" title="My orders" text={`${orders.length} orders and delivery status`} onPress={()=>navigation.navigate('Orders')}/></ScrollView>; }
function Sell() { const [name,setName]=useState('Tomato'); const [quantity,setQuantity]=useState(''); const [price,setPrice]=useState(''); const submit=async()=>{try{await api.post('/crops',{name,quantity,expectedPrice:price,unit:'Quintal',category:'Vegetables'});Alert.alert('Success','Crop listed successfully.');setQuantity('');setPrice('');}catch(e){Alert.alert('Could not list crop',e.message)}}; return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="Sell Crop" subtitle="Create a simple crop listing"/><Card><Text style={styles.label}>Crop name</Text><TextInput style={styles.input} value={name} onChangeText={setName}/><Text style={styles.label}>Quantity (Quintal)</Text><TextInput style={styles.input} value={quantity} onChangeText={setQuantity} keyboardType="numeric"/><Text style={styles.label}>Expected price (₹/Quintal)</Text><TextInput style={styles.input} value={price} onChangeText={setPrice} keyboardType="numeric"/><Pressable style={styles.primary} onPress={submit}><Text style={styles.primaryText}>List crop</Text></Pressable></Card></ScrollView>; }
function Market() { const [prices,setPrices]=useState([]); useEffect(()=>{api.get('/market-prices').then(r=>setPrices(r.data||[])).catch(()=>{});},[]); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="Market Intelligence" subtitle="Compare mandi prices before selling"/><Card><Text style={styles.section}>Live market prices</Text>{prices.slice(0,8).map((p,i)=><View style={styles.row} key={i}><View style={{flex:1}}><Text style={styles.actionTitle}>{p.commodity||'Crop'}</Text><Text style={styles.muted}>{p.market_name||p.district_name||'Market'}</Text></View><Text style={styles.price}>₹{p.modal_price ?? p.modalPrice ?? '--'}</Text></View>)}{!prices.length&&<Text style={styles.muted}>Market data will appear when the backend is available.</Text>}</Card></ScrollView>; }
function Orders() { const [orders,setOrders]=useState([]); useEffect(()=>{api.get('/orders').then(r=>setOrders(r.data||[])).catch(()=>{});},[]); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="My Orders" subtitle="Track sales and deliveries"/>{orders.map(o=><Card key={o.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.actionTitle}>{o.cropName} · {o.quantity} {o.unit}</Text><Text style={styles.muted}>{o.buyerName}</Text></View><Text style={styles.status}>{o.status}</Text></View><Text style={styles.price}>₹{o.finalAmount||0}</Text></Card>)}{!orders.length&&<Card><Text style={styles.muted}>No orders yet.</Text></Card>}</ScrollView>; }
function Transport() { const [crop,setCrop]=useState('Tomato'); const [qty,setQty]=useState(''); const [pickup,setPickup]=useState(''); const [delivery,setDelivery]=useState(''); const submit=()=>Alert.alert('Transport request','Your transport request is ready to connect to the existing transporter workflow.'); return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="Book Transportation" subtitle="Farm pickup to buyer delivery"/><Card><Text style={styles.label}>Crop</Text><TextInput style={styles.input} value={crop} onChangeText={setCrop}/><Text style={styles.label}>Quantity</Text><TextInput style={styles.input} value={qty} onChangeText={setQty} keyboardType="numeric"/><Text style={styles.label}>Pickup location</Text><TextInput style={styles.input} value={pickup} onChangeText={setPickup} placeholder="Your farm / village"/><Text style={styles.label}>Delivery location</Text><TextInput style={styles.input} value={delivery} onChangeText={setDelivery} placeholder="Buyer / market"/><Pressable style={styles.primary} onPress={submit}><Text style={styles.primaryText}>Request transport</Text></Pressable></Card></ScrollView>; }
function Profile({ onLogout }) { return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Header title="My Profile" subtitle="Farmer account"/><Card><Action icon="person-circle" title="Farmer profile" text="Manage your farm and contact details"/><Action icon="language" title="Language" text="Ready for regional-language support"/><Action icon="notifications" title="Notifications" text="Market and order alerts"/></Card><Pressable style={styles.danger} onPress={onLogout}><Text style={styles.dangerText}>Log out</Text></Pressable></ScrollView>; }
function MainTabs({ onLogout }) { return <Tabs.Navigator screenOptions={({route})=>({headerShown:false,tabBarActiveTintColor:green,tabBarLabelStyle:{fontWeight:'700'},tabBarIcon:({color,size})=><Ionicons name={route.name==='Home'?'home':route.name==='Market'?'analytics':route.name==='Sell'?'add-circle':route.name==='Orders'?'cube':'person'} color={color} size={size}})}><Tabs.Screen name="Home" component={Home}/><Tabs.Screen name="Market" component={Market}/><Tabs.Screen name="Sell" component={Sell}/><Tabs.Screen name="Orders" component={Orders}/><Tabs.Screen name="Profile">{()=> <Profile onLogout={onLogout}/>}</Tabs.Screen></Tabs.Navigator>; }
export default function App(){const [logged,setLogged]=useState(false); useEffect(()=>{AsyncStorage.getItem('agrinova-token').then(t=>setLogged(!!t));},[]); return <SafeAreaProvider><NavigationContainer>{logged?<MainTabs onLogout={async()=>{await logout();setLogged(false)}}/>:<Stack.Navigator screenOptions={{headerShown:false}}><Stack.Screen name="Login">{()=> <Login onDone={()=>setLogged(true)}/>}</Stack.Screen></Stack.Navigator>}</NavigationContainer></SafeAreaProvider>;}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:light},content:{padding:18,paddingBottom:36},header:{paddingTop:12,paddingBottom:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:14,fontWeight:'800',color:green},title:{fontSize:26,fontWeight:'900',color:'#0f172a',marginTop:2},muted:{fontSize:13,color:'#64748b',lineHeight:19},avatar:{width:44,height:44,borderRadius:22,backgroundColor:'#dcfce7',alignItems:'center',justifyContent:'center'},card:{backgroundColor:'white',borderRadius:20,padding:18,marginBottom:14,borderWidth:1,borderColor:'#dcfce7'},section:{fontSize:18,fontWeight:'900',color:'#0f172a',marginBottom:10},big:{fontSize:32,fontWeight:'900',color:green},link:{color:green,fontWeight:'800',marginTop:12},action:{backgroundColor:'white',borderRadius:18,padding:15,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#e2e8f0'},icon:{width:48,height:48,borderRadius:15,backgroundColor:'#dcfce7',alignItems:'center',justifyContent:'center'},actionTitle:{fontSize:15,fontWeight:'800',color:'#0f172a'},row:{flexDirection:'row',alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#f1f5f9'},price:{fontSize:17,fontWeight:'900',color:green},status:{fontSize:11,fontWeight:'800',color:green,backgroundColor:'#dcfce7',paddingHorizontal:9,paddingVertical:5,borderRadius:10},label:{fontSize:13,fontWeight:'800',color:'#334155',marginBottom:7,marginTop:8},input:{backgroundColor:'#f8fafc',borderWidth:1,borderColor:'#cbd5e1',borderRadius:14,paddingHorizontal:14,paddingVertical:13,fontSize:15,marginBottom:6},primary:{backgroundColor:green,borderRadius:15,padding:15,alignItems:'center',marginTop:14,minHeight:50,justifyContent:'center'},primaryText:{color:'white',fontWeight:'900',fontSize:15},danger:{backgroundColor:'#fee2e2,borderRadius:15,padding:15,alignItems:'center',marginTop:10},dangerText:{color:'#b91c1c',fontWeight:'900'},login:{flex:1,backgroundColor:light,padding:24,justifyContent:'center'},logo:{fontSize:64,textAlign:'center',marginBottom:12},loginTitle:{fontSize:30,fontWeight:'900',textAlign:'center',color:'#0f172a'},loginSub:{fontSize:15,textAlign:'center',color:'#64748b',marginBottom:28},hint:{fontSize:12,color:'#64748b',textAlign:'center',marginTop:18}}
